---
- name: Ensure znc compose file
  ansible.builtin.copy:
    src: compose.yml
    dest: "{{ base_dir }}/irc/compose.yml"

- name: Ensure znc service with compose
  community.docker.docker_compose_v2:
    project_src: "{{ base_dir }}/irc"
    docker_cli: /usr/local/bin/docker
