---
- name: Ensure lubelogger compose file
  ansible.builtin.template:
    src: compose.j2
    dest: "{{ base_dir }}/lubelogger/compose.yml"
    mode: "0644"

- name: Ensure lubelogger service with compose
  community.docker.docker_compose_v2:
    project_src: "{{ base_dir }}/lubelogger"
    docker_cli: /usr/local/bin/docker
